### ISSUE TITLE
TryGetValueByName throws

### ISSUE THREAD

**Issue by ldy985** [LordMike/MBW.Utilities.ManagedSqlite#12]
I am trying to parse a database from the Windows Store, but for some reason TryGetValueByName throws an exception. This seems like unexpected behavior.

[db.zip](https://github.com/LordMike/MBW.Utilities.ManagedSqlite/files/7323356/db.zip)
```
System.ArgumentException: An item with the same key has already been added. Key: FOREIGN
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at MBW.Utilities.ManagedSqlite.Sql.SqlTableDefinition.AddColumn(SqlTableColumn column)
   at MBW.Utilities.ManagedSqlite.Sql.SqlParser.TryParse(String sql, SqlTableDefinition& tableDefinition)
   at MBW.Utilities.ManagedSqlite.Sql.SqlExtensions.GetTableDefinition(Sqlite3SchemaRow schema)
   at MBW.Utilities.ManagedSqlite.Sql.SqlExtensions.GetTableDefinition(Sqlite3Table table)
   at MBW.Utilities.ManagedSqlite.Sql.SqlExtensions.TryGetValueByName(Sqlite3Row row, String columnName, Object& value)
   at MBW.Utilities.ManagedSqlite.Sql.SqlExtensions.TryGetValueByName[T](Sqlite3Row row, String columnName, T& value)
```

**Comment by LordMike** [comment]
It borked on parsing the following. Turns out you can define FOREIGN KEY constraints _after_ all columns (of course..).

I've added all `table-constraint` keywords to a list of ignores for columns.

```
CREATE TABLE WowDependencyGraph
(
	_WowDependencyGraphID INTEGER PRIMARY KEY NOT NULL,
	_Revision INTEGER NOT NULL DEFAULT 1,
	_WorkId INTEGER NOT NULL DEFAULT 0,
	_ShadowId INTEGER NOT NULL DEFAULT 0,
	_IsMarkedForDeletion INTEGER NOT NULL DEFAULT 0,
	User INTEGER NOT NULL,
	DependentPackage INTEGER NOT NULL,
	"Index" INTEGER NOT NULL DEFAULT 0,
	SupplierPackage INTEGER NOT NULL,
	DependencyType INTEGER NOT NULL,
	_Dictionary BLOB,
	FOREIGN KEY(User) REFERENCES User(_UserID),
	FOREIGN KEY(DependentPackage) REFERENCES Package(_PackageID),
	FOREIGN KEY(SupplierPackage) REFERENCES Package(_PackageID)
)
```
